server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?servetTimeZone=UTC&characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: kong20000519.@
